### ISSUE TITLE
CoreProtect v23.1 - Not working on 1.21.10

### ISSUE THREAD

**Issue by legendofgow** [PlayPro/CoreProtect#832]
Paper 1.21.10
Error on startup

`[11:39:51] [Server thread/INFO]: [CoreProtect] Enabling CoreProtect v23.1
[11:39:51] [Server thread/ERROR]: Error occurred while enabling CoreProtect v23.1 (Is it up to date?)
java.lang.NoClassDefFoundError: net/coreprotect/config/ConfigHandler
	at CoreProtect-CE-23.1.jar/net.coreprotect.CoreProtect.onEnable(CoreProtect.java:45) ~[CoreProtect-CE-23.1.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:279) ~[paper-api-1.21.10-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.10.jar:1.21.10-115-af06383]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.10.jar:1.21.10-115-af06383]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21.10-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:639) ~[paper-1.21.10.jar:1.21.10-115-af06383]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:596) ~[paper-1.21.10.jar:1.21.10-115-af06383]
	at net.minecraft.server.MinecraftServer.initPostWorld(MinecraftServer.java:637) ~[paper-1.21.10.jar:1.21.10-115-af06383]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:368) ~[paper-1.21.10.jar:1.21.10-115-af06383]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1257) ~[paper-1.21.10.jar:1.21.10-115-af06383]
	at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:384) ~[paper-1.21.10.jar:1.21.10-115-af06383]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.coreprotect.config.ConfigHandler
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:208) ~[paper-api-1.21.10-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:175) ~[paper-api-1.21.10-R0.1-SNAPSHOT.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	... 12 more
[11:39:51] [Server thread/INFO]: [CoreProtect] Disabling CoreProtect v23.1
[11:39:51] [Server thread/ERROR]: Error occurred while disabling CoreProtect v23.1`
