### ISSUE TITLE
update to 1.20.6

### ISSUE THREAD

**Issue by ghost** [PlayPro/CoreProtect#536]

**Comment by PukPukov** [comment]
As far as I see, last version works on 1.20.6.

**Comment by PukPukov** [comment]
Nah, this error spams console:

`[11:06:33 ERROR]: Could not pass event ProjectileLaunchEvent to CoreProtect v22.2
java.lang.NoSuchMethodError: 'org.bukkit.potion.PotionData org.bukkit.entity.Arrow.getBasePotionData()'
        at CoreProtect-22.2.jar/net.coreprotect.listener.PlayerPickupArrowListener.getArrowType(PlayerPickupArrowListener.java:34) ~[C
oreProtect-22.2.jar:?]
        at CoreProtect-22.2.jar/net.coreprotect.listener.player.ProjectileLaunchListener.onProjectileLaunch(ProjectileLaunchListener.j
ava:85) ~[CoreProtect-22.2.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[leaf-api-1.20
.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:72) ~[leaf-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:66) ~[leaf-1.20.6.jar:git-Leaf-"a46d325"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[leaf-1.20.6.jar:git-Leaf-"a46d325"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[leaf-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callProjectileLaunchEvent(CraftEventFactory.java:1480) ~[?:?]
        at org.bukkit.craftbukkit.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:707) ~[?:?]
        at net.minecraft.server.level.ServerLevel.addEntity(ServerLevel.java:1712) ~[?:?]
        at net.minecraft.server.level.ServerLevel.addFreshEntity(ServerLevel.java:1634) ~[?:?]
        at net.minecraft.server.level.ServerLevel.addFreshEntity(ServerLevel.java:1629) ~[?:?]
        at net.minecraft.world.item.ProjectileWeaponItem.shoot(ProjectileWeaponItem.java:76) ~[?:?]
        at net.minecraft.world.item.BowItem.releaseUsing(BowItem.java:34) ~[?:?]
        at net.minecraft.world.item.ItemStack.releaseUsing(ItemStack.java:949) ~[leaf-1.20.6.jar:git-Leaf-"a46d325"]
        at net.minecraft.world.entity.LivingEntity.releaseUsingItem(LivingEntity.java:4201) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1894) ~[?:?]        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:51) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.a(ServerboundPlayerActionPacket.java:20) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:54) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[leaf-1.20.6.jar:git-Leaf-"a46d325"]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1520) ~[leaf-1.20.6.jar:git-Leaf-"a46d325"]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:187) ~[leaf-1.20.6.jar:git-Leaf-"a46d325"]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1498) ~[leaf-1.20.6.jar:git-Leaf-"a46d325"]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1426) ~[leaf-1.20.6.jar:git-Leaf-"a46d325"]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1391) ~[leaf-1.20.6.jar:git-Leaf-"a46d325"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1254) ~[leaf-1.20.6.jar:git-Leaf-"a46d325"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[leaf-1.20.6.jar:git-Leaf-"a46d325"]
        at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]`

**Comment by CyberFlameGO** [comment]
Can reproduce the above error output too

**Comment by vacla** [comment]
@PukPukov @CyberFlameGO that is already fixed in https://github.com/PlayPro/CoreProtect/commit/053f7d5c7deabb9b7263436427ff8ea7b1ee9ae5

**Comment by CyberFlameGO** [comment]
My baddd - will the jar be released or should I build it if I want it?
